Repository colorlessenergy/a-inventory-system, pull requests merged in 2019-06, with the labels that each got.

#55 add functionality for a user to update an item as per #47
  inventory-system-api/controllers/items.js
  inventory-system-api/routes/itemsRouter.js
Labels: enhancement

#56 add reusable Form component as per #54
  inventory-system-frontend/src/Components/UI/Form/Form.js
Labels: enhancement

#59 add the reusable component to the Item container to display items as per issue #58
  inventory-system-frontend/src/containers/Items/Items.js
Labels: enhancement

#64 use Form component in Register, and Login as per #57
  inventory-system-frontend/src/containers/Login/Login.js
  inventory-system-frontend/src/containers/Register/Register.js
Labels: enhancement

#69 add styling to form and body as per issue #68
  inventory-system-frontend/public/index.html
  inventory-system-frontend/src/Components/UI/Form/Form.js
  inventory-system-frontend/src/Components/UI/Form/form.module.css
  inventory-system-frontend/src/index.css
Labels: enhancement

#71 move addItem component into a separate route as per issue #70
  inventory-system-frontend/src/App.js
  inventory-system-frontend/src/containers/Items/AddItem.js
  inventory-system-frontend/src/containers/Items/AddItem.module.css
  inventory-system-frontend/src/containers/Items/Items.js
Labels: enhancement

#79 add axios request to UpdateItemComponent as per #78
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
Labels: enhancement

#87 hook up front end with back end as per issue #86
  inventory-system-api/controllers/users.js
  inventory-system-api/routes/usersRouter.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
  inventory-system-frontend/src/containers/Settings/UserSettings.js
Labels: enhancement

#88 add styles to room component as per #80 and update API
  inventory-system-api/controllers/rooms.js
  inventory-system-api/models/schemas/room.js
  inventory-system-frontend/src/Components/UI/List.js
  inventory-system-frontend/src/Components/UI/List.module.css
  inventory-system-frontend/src/containers/Rooms/AddRoom.js
  inventory-system-frontend/src/containers/Rooms/AddRoom.module.css
Labels: bug, enhancement

#90 explicit coercion salt rounds as per issue #89
  inventory-system-api/models/schemas/user.js
Labels: bug

#92 Bug/#91 login register not working
  inventory-system-api/controllers/auths.js
  inventory-system-api/controllers/users.js
  inventory-system-api/models/schemas/user.js
Labels: bug, enhancement

#95 create landing page and nav as per issue #94
  inventory-system-frontend/src/App.js
  inventory-system-frontend/src/Components/Home/Home.js
  inventory-system-frontend/src/Components/Home/Home.module.css
  inventory-system-frontend/src/Components/Nav/Nav.js
  inventory-system-frontend/src/Components/Nav/nav.module.css
Labels: enhancement

#98 update nav rendering logic and add redirects as per #97
  inventory-system-frontend/src/App.js
  inventory-system-frontend/src/Components/Nav/Nav.js
  inventory-system-frontend/src/Components/Settings.js
  inventory-system-frontend/src/containers/Items/Items.js
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
  inventory-system-frontend/src/containers/Login/Login.js
  inventory-system-frontend/src/containers/Register/Register.js
  inventory-system-frontend/src/containers/Rooms/Rooms.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
  inventory-system-frontend/src/containers/Settings/RoomsSettings.js
  inventory-system-frontend/src/containers/Settings/UserSettings.js
  inventory-system-frontend/src/redux/actions/itemsAction.js
  inventory-system-frontend/src/redux/actions/roomsAction.js
Labels: enhancement

#103 Enhancement/#101 add functionality delete room item
  inventory-system-api/routes/itemsRouter.js
  inventory-system-frontend/src/Components/UI/Form/Form.js
  inventory-system-frontend/src/Components/UI/Form/form.module.css
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
Labels: enhancement

#108 add styles to Item component, update API response, and make forms reactive as per #93
  inventory-system-api/controllers/rooms.js
  inventory-system-frontend/src/Components/UI/Form/Form.js
  inventory-system-frontend/src/Components/UI/List.js
  inventory-system-frontend/src/Components/UI/List.module.css
  inventory-system-frontend/src/containers/Items/AddItem.js
  inventory-system-frontend/src/containers/Items/Items.js
  inventory-system-frontend/src/containers/Items/Items.module.css
  inventory-system-frontend/src/containers/Rooms/AddRoom.js
  inventory-system-frontend/src/containers/Rooms/AddRoom.module.css
  inventory-system-frontend/src/redux/reducers/itemsReducer.js
Labels: enhancement

#111 Enhancement/#110 update api url
  inventory-system-frontend/src/services/Api.js
Labels: enhancement

#112 update go back link as per #109
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
Labels: enhancement

#114 setup buttons to edit and delete item as per issue #113
  inventory-system-frontend/src/Components/UI/List.js
  inventory-system-frontend/src/Components/UI/List.module.css
  inventory-system-frontend/src/assets/delete-icon.svg
  inventory-system-frontend/src/assets/edit-icon.svg
  inventory-system-frontend/src/containers/Items/Items.js
  inventory-system-frontend/src/redux/actions/itemsAction.js
  inventory-system-frontend/src/redux/reducers/itemsReducer.js
Labels: enhancement

#116 update condition for checking if property amount exists as per issue#115
  inventory-system-frontend/src/Components/UI/List.js
Labels: bug

#121 add form validation and clean up api as per #120
  inventory-system-api/controllers/auths.js
  inventory-system-api/controllers/items.js
  inventory-system-api/controllers/rooms.js
  inventory-system-api/controllers/users.js
  inventory-system-api/routes/itemsRouter.js
  inventory-system-api/routes/roomsRouter.js
  inventory-system-api/routes/usersRouter.js
  inventory-system-frontend/src/Components/UI/Error/Error.js
  inventory-system-frontend/src/Components/UI/Error/Error.module.css
  inventory-system-frontend/src/Components/UI/Form/Form.js
  inventory-system-frontend/src/Components/UI/Form/form.module.css
  inventory-system-frontend/src/containers/Items/AddItem.js
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
  inventory-system-frontend/src/containers/Login/Login.js
  inventory-system-frontend/src/containers/Register/Register.js
  inventory-system-frontend/src/containers/Rooms/AddRoom.js
  inventory-system-frontend/src/containers/Rooms/AddRoom.module.css
  inventory-system-frontend/src/containers/Rooms/Rooms.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
  inventory-system-frontend/src/containers/Settings/UserSettings.js
  inventory-system-frontend/src/services/Api.js
Labels: enhancement

#124 update button text as per #122
  inventory-system-api/package-lock.json
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
  inventory-system-frontend/src/containers/Settings/UserSettings.js
Labels: enhancement

#128 update authentication check as per #127
  inventory-system-frontend/src/App.js
  inventory-system-frontend/src/Components/Home/Home.js
  inventory-system-frontend/src/containers/Items/AddItem.js
  inventory-system-frontend/src/containers/Items/Items.js
  inventory-system-frontend/src/containers/Items/UpdateItem/UpdateItem.js
  inventory-system-frontend/src/containers/Rooms/AddRoom.js
  inventory-system-frontend/src/containers/Rooms/Rooms.js
  inventory-system-frontend/src/containers/Rooms/UpdateRoom.js
  inventory-system-frontend/src/containers/Settings/RoomsSettings.js
  inventory-system-frontend/src/containers/Settings/UserSettings.js
Labels: bug

#130 add icons and update manifest as per #129
  inventory-system-frontend/public/images/icons-192.png
  inventory-system-frontend/public/images/icons-512.png
  inventory-system-frontend/public/images/icons/android-chrome-192x192.png
  inventory-system-frontend/public/images/icons/android-chrome-512x512.png
  inventory-system-frontend/public/images/icons/apple-touch-icon-120x120.png
  inventory-system-frontend/public/images/icons/apple-touch-icon-152x152.png
  inventory-system-frontend/public/images/icons/apple-touch-icon-180x180.png
  inventory-system-frontend/public/images/icons/apple-touch-icon-60x60.png
  inventory-system-frontend/public/images/icons/apple-touch-icon-76x76.png
  inventory-system-frontend/public/images/icons/apple-touch-icon.png
  inventory-system-frontend/public/images/icons/favicon-16x16.png
  inventory-system-frontend/public/images/icons/favicon-32x32.png
  inventory-system-frontend/public/images/icons/msapplication-icon-144x144.png
  inventory-system-frontend/public/images/icons/mstile-150x150.png
  inventory-system-frontend/public/images/icons/safari-pinned-tab.svg
  inventory-system-frontend/public/manifest.json
Labels: enhancement
